const SHOW_ERROR = 'SHOW_ERROR';
const HIDE_ERROR = 'HIDE_ERROR';
const SHOW_LOADING = 'SHOW_LOADING';
const HIDE_LOADING = 'HIDE_LOADING';
const UPDATE_VEHICLES_LIST = 'UPDATE_VEHICLES_LIST';

export {
    SHOW_ERROR, 
    HIDE_ERROR,
    SHOW_LOADING,
    HIDE_LOADING,
    UPDATE_VEHICLES_LIST
}